export var ChrOpt = {
    sora1 : [
    {id: 'A_Sleepover_Close_By', name: 'A Sleepover Close By', image: 'images/sora/A_Sleepover_Close_By.webp'},
    {id: 'A_Sleepover_Close_By_Bloomed', name: 'A Sleepover Close By Bloomed', image: 'images/sora/A_Sleepover_Close_By_Bloomed.webp'},
    {id: 'Beyond_the_Illusion', name: 'Beyond the Illusion', image: 'images/sora/Beyond_the_Illusion.webp'},
    {id: 'Beyond_the_Illusion_Bloomed', name: 'Beyond the Illusion Bloomed', image: 'images/sora/Beyond_the_Illusion_Bloomed.webp'},
    {id: 'Cheerful_Rock', name: 'Cheerful Rock', image: 'images/sora/Cheerful_Rock.webp'},
    {id: 'Cheerful_Rock_Bloomed', name: 'Cheerful Rock Bloomed', image: 'images/sora/Cheerful_Rock_Bloomed.webp'},
    {id: 'Donning_the_Overlapping_Colors_of_Myself', name: 'Donning the Overlapping Colors of Myself', image: 'images/sora/Donning_the_Overlapping_Colors_of_Myself.webp'},
    {id: 'Donning_the_Overlapping_Colors_of_Myself_Bloomed', name: 'Donning the Overlapping Colors of Myself Bloomed', image: 'images/sora/Donning_the_Overlapping_Colors_of_Myself_Bloomed.webp'},
    {id: 'Feelings_of_Unfamiliarity', name: 'Feelings of Unfamiliarity', image: 'images/sora/Feelings_of_Unfamiliarity.webp'},
    {id: 'Feelings_of_Unfamiliarity_Bloomed', name: 'Feelings of Unfamiliarity Bloomed', image: 'images/sora/Feelings_of_Unfamiliarity_Bloomed.webp'},
    {id: 'Gentle_Interactions', name: 'Gentle Interactions', image: 'images/sora/Gentle_Interactions.webp'},
    {id: 'Gentle_Interactions_Bloomed', name: 'Gentle Interactions Bloomed', image: 'images/sora/Gentle_Interactions_Bloomed.webp'},
    {id: 'Glittering_Yellow_Comet', name: 'Glittering Yellow Comet', image: 'images/sora/Glittering_Yellow_Comet.webp'},
    {id: 'Glittering_Yellow_Comet_Bloomed', name: 'Glittering Yellow Comet Bloomed', image: 'images/sora/Glittering_Yellow_Comet_Bloomed.webp'},
    {id: 'Happy_Surprise', name: 'Happy Surprise', image: 'images/sora/Happy_Surprise.webp'},
    {id: 'Happy_Surprise_Bloomed', name: 'Happy Surprise Bloomed', image: 'images/sora/Happy_Surprise_Bloomed.webp'},
    {id: 'NewDi&#39;s_Smile', name: 'NewDi&#39;s Smile', image: 'images/sora/NewDi\'s_Smile.webp'},
    {id: 'NewDi&#39;s_Smile_Bloomed', name: 'NewDi&#39;s Smile Bloomed', image: 'images/sora/NewDi\'s_Smile_Bloomed.webp'},
    {id: 'Righteous_Thief', name: 'Righteous Thief', image: 'images/sora/Righteous_Thief.webp'},
    {id: 'Righteous_Thief_Bloomed', name: 'Righteous Thief Bloomed', image: 'images/sora/Righteous_Thief_Bloomed.webp'},
    {id: 'Skilled_Carat', name: 'Skilled Carat', image: 'images/sora/Skilled_Carat.webp'},
    {id: 'Skilled_Carat_Bloomed', name: 'Skilled Carat Bloomed', image: 'images/sora/Skilled_Carat_Bloomed.webp'},
    {id: 'Sky-Color_Crystal', name: 'Sky-Color Crystal', image: 'images/sora/Sky-Color_Crystal.webp'},
    {id: 'Sky-Color_Crystal_Bloomed', name: 'Sky-Color Crystal Bloomed', image: 'images/sora/Sky-Color_Crystal_Bloomed.webp'},
    {id: 'Sports_Festival_Specialty', name: 'Sports Festival Specialty', image: 'images/sora/Sports_Festival_Specialty.webp'},
    {id: 'Sports_Festival_Specialty_Bloomed', name: 'Sports Festival Specialty Bloomed', image: 'images/sora/Sports_Festival_Specialty_Bloomed.webp'},
    {id: 'To_Know_the_Unknown', name: 'To Know the Unknown', image: 'images/sora/To_Know_the_Unknown.webp'},
    {id: 'To_Know_the_Unknown_Bloomed', name: 'To Know the Unknown Bloomed', image: 'images/sora/To_Know_the_Unknown_Bloomed.webp'},
],
    natsume1 : [
    {id: '(Compromise_is_Also_Friendship)_Natsume_Sakasaki_Frameless', name: '(Compromise is Also Friendship) Natsume Sakasaki Frameless', image: 'images/natsume/(Compromise_is_Also_Friendship)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Compromise_is_Also_Friendship)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Compromise is Also Friendship) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Compromise_is_Also_Friendship)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Cruise_of_Encounters)_Natsume_Sakasaki_Frameless', name: '(Cruise of Encounters) Natsume Sakasaki Frameless', image: 'images/natsume/(Cruise_of_Encounters)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Cruise_of_Encounters)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Cruise of Encounters) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Cruise_of_Encounters)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Duality_and_Surprise)_Natsume_Sakasaki_Frameless', name: '(Duality and Surprise) Natsume Sakasaki Frameless', image: 'images/natsume/(Duality_and_Surprise)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Duality_and_Surprise)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Duality and Surprise) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Duality_and_Surprise)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Flaring_Ideals)_Natsume_Sakasaki_Frameless', name: '(Flaring Ideals) Natsume Sakasaki Frameless', image: 'images/natsume/(Flaring_Ideals)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Flaring_Ideals)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Flaring Ideals) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Flaring_Ideals)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Foreknowing_Tiger)_Natsume_Sakasaki_Frameless', name: '(Foreknowing Tiger) Natsume Sakasaki Frameless', image: 'images/natsume/(Foreknowing_Tiger)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Foreknowing_Tiger)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Foreknowing Tiger) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Foreknowing_Tiger)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Guide_Harboring_Wishes)_Natsume_Sakasaki_Frameless', name: '(Guide Harboring Wishes) Natsume Sakasaki Frameless', image: 'images/natsume/(Guide_Harboring_Wishes)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Guide_Harboring_Wishes)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Guide Harboring Wishes) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Guide_Harboring_Wishes)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Leader_of_Magic)_Natsume_Sakasaki_Frameless', name: '(Leader of Magic) Natsume Sakasaki Frameless', image: 'images/natsume/(Leader_of_Magic)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Leader_of_Magic)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Leader of Magic) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Leader_of_Magic)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Magic_and_StarFes)_Natsume_Sakasaki_Frameless', name: '(Magic and StarFes) Natsume Sakasaki Frameless', image: 'images/natsume/(Magic_and_StarFes)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Magic_and_StarFes)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Magic and StarFes) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Magic_and_StarFes)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(NewDi&#39;s_Eccentric)_Natsume_Sakasaki_Frameless', name: '(NewDi&#39;s Eccentric) Natsume Sakasaki Frameless', image: 'images/natsume/(NewDi\'s_Eccentric)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(NewDi&#39;s_Eccentric)_Natsume_Sakasaki_Frameless_Bloomed', name: '(NewDi&#39;s Eccentric) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(NewDi\'s_Eccentric)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Payment_for_Divination)_Natsume_Sakasaki_Frameless', name: '(Payment for Divination) Natsume Sakasaki Frameless', image: 'images/natsume/(Payment_for_Divination)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Payment_for_Divination)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Payment for Divination) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Payment_for_Divination)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Reassuring_Rock)_Natsume_Sakasaki_Frameless', name: '(Reassuring Rock) Natsume Sakasaki Frameless', image: 'images/natsume/(Reassuring_Rock)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Reassuring_Rock)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Reassuring Rock) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Reassuring_Rock)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(Scheming_AtoZ)_Natsume_Sakasaki_Frameless', name: '(Scheming AtoZ) Natsume Sakasaki Frameless', image: 'images/natsume/(Scheming_AtoZ)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(Scheming_AtoZ)_Natsume_Sakasaki_Frameless_Bloomed', name: '(Scheming AtoZ) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(Scheming_AtoZ)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(The_God_of_Shinsekai)_Natsume_Sakasaki_Frameless', name: '(The God of Shinsekai) Natsume Sakasaki Frameless', image: 'images/natsume/(The_God_of_Shinsekai)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(The_God_of_Shinsekai)_Natsume_Sakasaki_Frameless_Bloomed', name: '(The God of Shinsekai) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(The_God_of_Shinsekai)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(The_Liar_Game)_Natsume_Sakasaki_Frameless', name: '(The Liar Game) Natsume Sakasaki Frameless', image: 'images/natsume/(The_Liar_Game)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(The_Liar_Game)_Natsume_Sakasaki_Frameless_Bloomed', name: '(The Liar Game) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(The_Liar_Game)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
    {id: '(True_Meaning_and_Blessings)_Natsume_Sakasaki_Frameless', name: '(True Meaning and Blessings) Natsume Sakasaki Frameless', image: 'images/natsume/(True_Meaning_and_Blessings)_Natsume_Sakasaki_Frameless.webp'},
    {id: '(True_Meaning_and_Blessings)_Natsume_Sakasaki_Frameless_Bloomed', name: '(True Meaning and Blessings) Natsume Sakasaki Frameless Bloomed', image: 'images/natsume/(True_Meaning_and_Blessings)_Natsume_Sakasaki_Frameless_Bloomed.webp'},
],
}
