name: 
img:
  - unit: 
    summer: 
    winter: 
features:
  - Age: 
    Graduated From:
    Circles: 
    Unit: 
    Height: 
    Date of Birth: 
    Roomates: 
    Handedness: 
    Blood Type:
    Likes: 
    Dislikes: 
    Favorite Food: 
    Family:
    Hobby:
    Specialty:
    Image Color:
    Signature:
art: