firstname: 
surname: 
namejp: 
title: 
quote: 
icon: 
img:
  - unit: /my_boys/images/
    summer: /my_boys/images/
    winter: /my_boys/images/
features:
  - Age: 
    Graduated From:
    Circles: 
    Unit: 
    Height: 
    Date of Birth: 
    Roomates: 
    Handedness: 
    Blood Type: 
    Likes: 
    Dislikes: 
    Favorite Food: 
    Family:
    Hobby: 
    Specialty:
    Image Color:
    Signature:
art:
  - 1: 
relationships:
  - firstname: 
    surname: 
    icon: 
    link: 
    relates: 
    related: 
    feels: 
    felt: 
    calls:  
    called: 